### PR TITLE
Fix output file error

### LINKED ISSUE #63: Better error message when output folder does not exist
## Description

When the output folder for some reason is not writeable (like permissions or if it simply does not exist), xcribe crashes with an unfriendly error message:

image

## Expected behavior

I think a more descriptive error message should be displayed.

### PR DESCRIPTION
**Pull request by brosquinha**
## Motivation

When the output folder or file for some reason is not writeable (like missing write permissions or it simply does not exist), Xcribe crashes with an unfriendly error message. 

## Proposed solution

- Adds friendly error message (fixes #63).
image

### CODE REVIEW

**Review by adrianolisboa — APPROVED** [review]
👏🏾

File: test/xcribe/writter_test.exs [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+  import ExUnit.CaptureIO
+
+  alias Xcribe.Writter
+
+  @output_path "/tmp/test"
+  @invalid_output_path "/root/null"
+
+  describe "write/1" do
+    test "writes given text to set output directory" do
+      Application.put_env(:xcribe, :output, @output_path)
```
Comment (Danielwsx64) [inline test/xcribe/writter_test.exs:13]: Its important add a `setup` to tests to restore original `output` config (or just remove this config) to avoid mess up other test cases.

File: test/xcribe/writter_test.exs [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+
+      assert capture_io(fn ->
+               assert :ok == Writter.write("sample test")
+             end) =~ "Xcribe documentation written in #{@output_path}"
```
Comment (Danielwsx64) [inline test/xcribe/writter_test.exs:17]: It would be nice verify if the file was really written.

```suggestion
             end) =~ "Xcribe documentation written in #{@output_path}"
     
     assert File.read!(@output_path) == "sample test"
```

File: test/xcribe/writter_test.exs [hunk 3]
```diff
@@ -0,0 +1,28 @@
+defmodule Xcribe.WritterTest do
+  use ExUnit.Case, async: false
+
+  import ExUnit.CaptureIO
+
+  alias Xcribe.Writter
+
+  @output_path "/tmp/test"
```
Comment (Danielwsx64) [inline test/xcribe/writter_test.exs:8]: `test` is a very common name and it's possible already has a file with this name. Perhaps, to validate the file has been written in all test runs we should generate a random file name.

```elixir
output_path = "/tmp/xcribe_#{:rand.uniform()}"

**Review by Danielwsx64 — COMMENTED** [review]
🚀 💙

File: test/xcribe/writter_test.exs (hunk 1 above)
Comment (brosquinha) [reply test/xcribe/writter_test.exs]: Done :+1:

File: test/xcribe/writter_test.exs (hunk 2 above)
Comment (brosquinha) [reply test/xcribe/writter_test.exs]: Oops :sweat_smile:

**Review by Danielwsx64 — APPROVED** [review]
